# Generated by Django 4.0.3 on 2022-03-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supertypes',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
